Adding login page
beyond-io/shlifim pull request #95
Opened 2021-05-03 20:19 UTC by idokk1

Add Django built in login page. 
Because it's implemented by Django I didn't add tests for that (like login to admin page) except for test approaching /login url.
fix #94

2021-05-10 06:06 UTC, ifireball requested changes
Needs more tests, the fat that you are using Django's app is an implementation detail. How do you know login to your app actually works. The test should help you detect situations where you misconfigure Django or if a Django version update would break the functionality for you.

2021-05-10 06:06 UTC, ifireball commented on home/tests.py
> +    assert response.status_code == 301
I'd expect a bit more then that - for example, where are you being redirected to?

2021-05-10 21:39 UTC, idokk1 commented
Added another tests.

2021-05-10 21:54 UTC, avivz450 commented
LGTM

2021-05-10 22:59 UTC, danitLevi commented
LGTM

2021-05-11 05:18 UTC, ifireball approved these changes

2021-05-11 05:18 UTC, merged